const actionType = {
  SEARCH_HOTEL_INITIATION_SUCCESS: "SEARCH_HOTEL_INITIATION_SUCCESS",
  SEARCH_HOTEL_STATUS_SUCCESS: "SEARCH_HOTEL_STATUS_SUCCESS",
  CLEAR_HOTEL_LIST_SUCCESS: "CLEAR_HOTEL_LIST_SUCCESS",
  SEARCH_HOTEL_LIST_GET_SUCCESS: "SEARCH_HOTEL_LIST_GET_SUCCESS",
  SEARCH_HOTEL_LIST_GET_FAILURE: "SEARCH_HOTEL_LIST_GET_FAILURE",
  ENABLE_LOADING_SEARCH: "ENABLE_LOADING_SEARCH",
  DISABLE_LOADING_SEARCH: "DISABLE_LOADING_SEARCH",
}
export default actionType;